<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FB</name>
   <tag></tag>
   <elementGuidId>e8cb0412-42fc-468d-bc22-c7e4fc07d5b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Bold &amp; Underline Communication'])[2]/following::*[name()='svg'][4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>4d36eb71-77b5-40a9-91a2-f5631b88621e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>4319a454-16d1-499b-be0d-88698f88999f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>7e52a109-fd6a-46c1-ad4a-6a0ea297a005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>049ebf00-1141-4f12-aee2-b7fe65510d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 320 512</value>
      <webElementGuid>94de741c-f4db-4043-ad5e-25eefc56ce54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>8012374f-64ba-4317-b6e3-a0f53807ca25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>aa147624-f6b4-4764-9dbf-21493913b7a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>0f255681-7d27-465f-a6b8-2c689b41554a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative w-full overflow-hidden&quot;]/div[@class=&quot;fixed bottom-0 flex flex-col gap-[0.8rem] sm:flex-row justify-between items-center text-center w-full px-4 my-6 sm:px-8 sm:my-8 z-50&quot;]/div[@class=&quot;text-white text-xl&quot;]/ul[@class=&quot;flex justify-center items-center gap-5&quot;]/li[3]/a[@class=&quot;block cursor-pointer text-white text-opacity-60 hover:text-opacity-100&quot;]/svg[1]</value>
      <webElementGuid>eec237c1-1352-49da-9950-279330e551a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bold &amp; Underline Communication'])[2]/following::*[name()='svg'][4]</value>
      <webElementGuid>f9aaaa7c-bb37-4985-b7d0-50b3d80e7009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[1]/following::*[name()='svg'][4]</value>
      <webElementGuid>bfe3d209-f5b8-41fa-b2f0-186be36e9ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bold &amp; Underline'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>e2463c4b-ffdc-4ec2-abf4-f87abebe70a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creative Studio'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>c6608aba-85dd-4797-8a09-85d2a4fad437</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
