<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IG</name>
   <tag></tag>
   <elementGuidId>a8e94ac8-9592-4119-9d09-8c6e6b27f1b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Bold &amp; Underline Communication'])[2]/following::*[name()='svg'][3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>f0bb534b-1a85-426d-8b66-9fc6703e5809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>4a66a616-db8c-4c47-af1a-a2d990feffbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>da744b52-e6e9-43cf-b88b-cd402d83d4a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4357d0e4-b264-4448-bc34-78fd3a900868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 448 512</value>
      <webElementGuid>4ff84d64-cdba-4c89-bd81-750b4508ff9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>0732df6b-b019-4fd7-9c10-c363d8612e94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>4fe7bdae-5e78-4ce5-bc00-c8270e844076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>1aa521fe-e9b1-4d76-aef9-8a0a9b5a0d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative w-full overflow-hidden&quot;]/div[@class=&quot;fixed bottom-0 flex flex-col gap-[0.8rem] sm:flex-row justify-between items-center text-center w-full px-4 my-6 sm:px-8 sm:my-8 z-50&quot;]/div[@class=&quot;text-white text-xl&quot;]/ul[@class=&quot;flex justify-center items-center gap-5&quot;]/li[2]/a[@class=&quot;block cursor-pointer text-white text-opacity-60 hover:text-opacity-100&quot;]/svg[1]</value>
      <webElementGuid>a814ca6a-4b15-4819-9b65-28def5ce1182</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bold &amp; Underline Communication'])[2]/following::*[name()='svg'][3]</value>
      <webElementGuid>105fc654-00ad-4e41-973e-7a5ccf8842f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[1]/following::*[name()='svg'][3]</value>
      <webElementGuid>b9d3f8da-9535-45d7-96d8-49eb27fa7148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bold &amp; Underline'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>e04c401a-5590-4464-b277-d0139183b84c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creative Studio'])[1]/preceding::*[name()='svg'][4]</value>
      <webElementGuid>6685044a-2e41-41fc-a71f-2db50454394f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
