<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_WA</name>
   <tag></tag>
   <elementGuidId>9cd52048-8b86-40ac-a07c-98412dad47ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Bold &amp; Underline Communication'])[2]/following::*[name()='svg'][2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>fadbe456-0618-430a-acaa-1f8a4af64811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>5babd651-4a9f-4b5b-a9fc-c207b24b6804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>ca066fc8-d6ab-45c5-acca-e572cbb67325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f8e61454-d17c-41d1-9e5e-38f0244c2bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 448 512</value>
      <webElementGuid>4fbfb5f6-05c3-4cc2-8efc-6552c1abafa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>26df1c6e-bd2f-4673-9579-36dafea5f318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>b5656c35-10b0-4a8f-931d-58698bf3f35b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>7191cbeb-02a4-4053-8f79-91d0700bcd89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative w-full overflow-hidden&quot;]/div[@class=&quot;fixed bottom-0 flex flex-col gap-[0.8rem] sm:flex-row justify-between items-center text-center w-full px-4 my-6 sm:px-8 sm:my-8 z-50&quot;]/div[@class=&quot;text-white text-xl&quot;]/ul[@class=&quot;flex justify-center items-center gap-5&quot;]/li[1]/a[@class=&quot;block cursor-pointer text-white text-opacity-60 hover:text-opacity-100&quot;]/svg[1]</value>
      <webElementGuid>64cba5e7-dc38-4dba-b444-2a52b75f71f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bold &amp; Underline Communication'])[2]/following::*[name()='svg'][2]</value>
      <webElementGuid>a4eb04c3-c985-4fdd-84b0-7b5bd7257c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>107e18e8-e3e3-48bf-8669-c2e5586262e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bold &amp; Underline'])[1]/preceding::*[name()='svg'][4]</value>
      <webElementGuid>ae681126-ee0c-4d9c-81e3-6891b72b433c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creative Studio'])[1]/preceding::*[name()='svg'][5]</value>
      <webElementGuid>5f3ac180-972c-47a9-8a0a-5da8b54f939b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
