<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>M_Team</name>
   <tag></tag>
   <elementGuidId>c8393b59-28b5-4644-a1cf-cc49c379212f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/nav/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c60b8b3f-32ee-4330-bd3b-61110b1419a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block font-semibold uppercase tracking-widest whitespace-nowrap text-gray-300 hover:text-white hover:underline-offset-2 hover:underline transition</value>
      <webElementGuid>76e7ed78-3bb8-4975-97f3-949b87436a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/teams/</value>
      <webElementGuid>1c78de88-5f8d-4f37-9b2b-1dd8eb4284a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Team</value>
      <webElementGuid>327e1cb4-4b11-4d3c-8ac8-0a88b0d45fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative w-full overflow-hidden&quot;]/div[@class=&quot;fixed top-0 z-50 w-full my-6 px-4 sm:px-8 sm:my-8 transition&quot;]/nav[1]/ul[@class=&quot;flex justify-evenly sm:gap-10 sm:justify-start transition&quot;]/li[2]/a[@class=&quot;block font-semibold uppercase tracking-widest whitespace-nowrap text-gray-300 hover:text-white hover:underline-offset-2 hover:underline transition&quot;]</value>
      <webElementGuid>6d1ec102-7ec6-435a-b00b-85cefe69fe21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/nav/ul/li[2]/a</value>
      <webElementGuid>69e8f840-3db0-4629-beec-7038ce61c5b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Team')]</value>
      <webElementGuid>13b894c6-de5a-40da-9fd9-4c2a0014ea82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Services'])[1]/following::a[1]</value>
      <webElementGuid>cb9f121f-87f7-4874-9eac-a95c8900b95a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[1]/preceding::a[1]</value>
      <webElementGuid>7ff911e4-dd77-41f5-b17c-e3e7269c3a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bold &amp; Underline Communication'])[2]/preceding::a[2]</value>
      <webElementGuid>c50752e8-bd34-4d2d-8a7a-65cddebba621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Team']/parent::*</value>
      <webElementGuid>8781d008-1785-4413-beb4-3b1720cef70d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/teams/')]</value>
      <webElementGuid>c48af7d8-0eed-446e-aac8-419bc9f07292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>2d0636bd-dea7-4ea8-b863-6256b5f95123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/teams/' and (text() = 'Team' or . = 'Team')]</value>
      <webElementGuid>a16690de-7e27-466a-b65d-63ec216bea50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
