<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Devoskin_client</name>
   <tag></tag>
   <elementGuidId>5bdeb022-bb06-4981-8d9e-088120c305cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='our-client']/div/ul/li[3]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1e565d09-9ed5-4044-ba90-1338729436b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/img/klien/devoskin-logo.png</value>
      <webElementGuid>19a07dcc-cb25-4749-aaaf-9f8babde6334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo Devoskin</value>
      <webElementGuid>6cae402a-4976-4ac5-9ae9-2127faf86ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>0c1ce59d-d03f-4b8c-acbb-4ca00058b5ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>01cad737-2c37-44f0-bc82-39e3ba4a4f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>object-contain object-center</value>
      <webElementGuid>f098af50-1013-4070-b559-8a1c8f91328c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;our-client&quot;)/div[@class=&quot;w-full min-h-screen bg-slate-300 p-12 flex flex-col items-center justify-center&quot;]/ul[@class=&quot;logos flex flex-wrap justify-evenly gap-2 px-1 sm:gap-10 sm:px-16&quot;]/li[@class=&quot;relative w-32 h-32 mx-1 my-1 sm:w-36 sm:h-36 sm:mx-8 sm:my-4&quot;]/a[@class=&quot;relative flex w-full h-full&quot;]/img[@class=&quot;object-contain object-center&quot;]</value>
      <webElementGuid>181e9c65-6067-4321-9229-8993f9e92bd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='our-client']/div/ul/li[3]/a/img</value>
      <webElementGuid>0341e61c-854e-4294-8c1c-35734a624eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Logo Devoskin']</value>
      <webElementGuid>a7779d93-9f0e-4ba9-9ce2-434a0ad5cfbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/img</value>
      <webElementGuid>9393a2a7-41f4-4db9-a09d-442eff6af5ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/img/klien/devoskin-logo.png' and @alt = 'Logo Devoskin']</value>
      <webElementGuid>6abf36d1-3a00-415f-aace-fe47aae0f49c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
