<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>elgan_client</name>
   <tag></tag>
   <elementGuidId>e30feaf3-6c41-4e64-825b-b720b3ec3bd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='our-client']/div/ul/li/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.object-contain.object-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>aa7adacf-d9ef-430a-a2db-2b31154863aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/img/klien/elgan-logo.png</value>
      <webElementGuid>70996268-4630-4021-bfea-acbb81e04843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo Elgan</value>
      <webElementGuid>c5c00ff2-dcd1-40c6-9f00-0af95cce98b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>e5deb7a9-0b5d-4f92-80a7-d55586293ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>e139506b-ceab-4db2-ae75-82810ea011ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>object-contain object-center</value>
      <webElementGuid>bc304def-3ba1-4105-b75b-25c8534e71ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;our-client&quot;)/div[@class=&quot;w-full min-h-screen bg-slate-300 p-12 flex flex-col items-center justify-center&quot;]/ul[@class=&quot;logos flex flex-wrap justify-evenly gap-2 px-1 sm:gap-10 sm:px-16&quot;]/li[@class=&quot;relative w-32 h-32 mx-1 my-1 sm:w-36 sm:h-36 sm:mx-8 sm:my-4&quot;]/a[@class=&quot;relative flex w-full h-full&quot;]/img[@class=&quot;object-contain object-center&quot;]</value>
      <webElementGuid>f81bcd9e-bd2b-4d53-ace9-6c224bda76ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='our-client']/div/ul/li/a/img</value>
      <webElementGuid>10a33d36-9972-4d24-94a5-750c4c0b20ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Logo Elgan']</value>
      <webElementGuid>844d9d33-a95d-4725-92f9-6fbdf56bfcdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>bf81bc30-0443-4b34-81ba-475e91f3373f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/img/klien/elgan-logo.png' and @alt = 'Logo Elgan']</value>
      <webElementGuid>8fe65e21-c068-4c94-a9e0-b9a45166c7a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
