<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hutaFM_client</name>
   <tag></tag>
   <elementGuidId>accc8143-29db-44e5-ba9d-017b58770e36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='our-client']/div/ul/li[4]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c72d0193-6157-4551-a642-044a51db8aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/img/klien/huta-logo.png</value>
      <webElementGuid>a6117f8f-62d1-48ec-a160-112c0b033676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo Huta Fresh Market</value>
      <webElementGuid>68e35dce-a6a0-48a2-9c36-c0d2dc63b60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>abc05de5-f6ac-4f69-a9bc-5810b736c23f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>4e125493-4e83-4596-bd1e-530ace7c3056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>object-contain object-center</value>
      <webElementGuid>7096064f-e6ea-4904-80fa-6a75dc48b5f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;our-client&quot;)/div[@class=&quot;w-full min-h-screen bg-slate-300 p-12 flex flex-col items-center justify-center&quot;]/ul[@class=&quot;logos flex flex-wrap justify-evenly gap-2 px-1 sm:gap-10 sm:px-16&quot;]/li[@class=&quot;relative w-32 h-32 mx-1 my-1 sm:w-36 sm:h-36 sm:mx-8 sm:my-4&quot;]/a[@class=&quot;relative flex w-full h-full&quot;]/img[@class=&quot;object-contain object-center&quot;]</value>
      <webElementGuid>844ff1b7-4bd7-46c6-ab6f-ed07ea254213</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='our-client']/div/ul/li[4]/a/img</value>
      <webElementGuid>27694d83-9967-46fc-ac34-0956f151f09a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Logo Huta Fresh Market']</value>
      <webElementGuid>9b441d52-208e-4ede-b796-1299bfb4eead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/img</value>
      <webElementGuid>ce060849-d43d-4ca1-b51e-7b65824032b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/img/klien/huta-logo.png' and @alt = 'Logo Huta Fresh Market']</value>
      <webElementGuid>b94e1015-e3d4-430d-803c-6422ce6bb6ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
