<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>kefi_client</name>
   <tag></tag>
   <elementGuidId>b81901ce-3ede-483d-bb5a-66bbd68766a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='our-client']/div/ul/li[5]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6c69e0cf-aeed-4128-a878-37265756cfc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/img/klien/kefi-logo.png</value>
      <webElementGuid>f7fb5d37-271b-47f6-9428-ed7ecb8ffc1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo Kefi Cafe and Space</value>
      <webElementGuid>c36f1487-4689-4ecb-a75f-ae8b4bc1205f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>d675bbbd-35c5-4d16-8350-d4d40b570add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>61dbeace-4954-44d1-89ed-e0d499dcf640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>object-contain object-center</value>
      <webElementGuid>51ccbca1-9ab8-4ae3-ae9e-a48b168bce0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;our-client&quot;)/div[@class=&quot;w-full min-h-screen bg-slate-300 p-12 flex flex-col items-center justify-center&quot;]/ul[@class=&quot;logos flex flex-wrap justify-evenly gap-2 px-1 sm:gap-10 sm:px-16&quot;]/li[@class=&quot;relative w-32 h-32 mx-1 my-1 sm:w-36 sm:h-36 sm:mx-8 sm:my-4&quot;]/a[@class=&quot;relative flex w-full h-full&quot;]/img[@class=&quot;object-contain object-center&quot;]</value>
      <webElementGuid>35a39504-0434-4b52-8575-d75e5195ee7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='our-client']/div/ul/li[5]/a/img</value>
      <webElementGuid>e15abd4d-c62b-4753-858b-a95a2c2197bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Logo Kefi Cafe and Space']</value>
      <webElementGuid>0b96162b-b658-42d6-89b9-249de6f0f756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/img</value>
      <webElementGuid>86ee7d58-a583-4abe-9a67-13b0cf9ae4a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/img/klien/kefi-logo.png' and @alt = 'Logo Kefi Cafe and Space']</value>
      <webElementGuid>9f253c7c-4ce3-4cc7-b4bc-e13042a8e753</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
