<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Polantas_client</name>
   <tag></tag>
   <elementGuidId>d6b63bf9-3930-42bd-acdf-90ca9cd22692</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='our-client']/div/ul/li[2]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ad0ede4f-6585-4d93-a975-cf3ab3d48125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/img/klien/ditlantaspoldasumut-logo.png</value>
      <webElementGuid>60f3ce25-bca5-413b-8c68-05834f45761a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo Direktorat Lalu Lintas Polda Sumut</value>
      <webElementGuid>330bb545-1061-47de-a111-a04780f4e23d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>529b87f1-5303-42d5-b228-0d93c77d456f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>8c03a067-c5c9-470b-8d0a-2091aacd3188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>object-contain object-center</value>
      <webElementGuid>80b22f62-eb78-4ea3-8c6d-a24734dabfd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;our-client&quot;)/div[@class=&quot;w-full min-h-screen bg-slate-300 p-12 flex flex-col items-center justify-center&quot;]/ul[@class=&quot;logos flex flex-wrap justify-evenly gap-2 px-1 sm:gap-10 sm:px-16&quot;]/li[@class=&quot;relative w-32 h-32 mx-1 my-1 sm:w-36 sm:h-36 sm:mx-8 sm:my-4&quot;]/a[@class=&quot;relative flex w-full h-full&quot;]/img[@class=&quot;object-contain object-center&quot;]</value>
      <webElementGuid>86e57e62-9b68-4347-b91e-199d56d364c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='our-client']/div/ul/li[2]/a/img</value>
      <webElementGuid>1ec5972f-00e6-4f01-9190-bccd197fea17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Logo Direktorat Lalu Lintas Polda Sumut']</value>
      <webElementGuid>6d4ae28a-d5e0-45f0-8daa-8aa593c9951f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/img</value>
      <webElementGuid>721e5655-636b-4116-86e5-a043b69cd224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/img/klien/ditlantaspoldasumut-logo.png' and @alt = 'Logo Direktorat Lalu Lintas Polda Sumut']</value>
      <webElementGuid>36704241-74d4-47a3-b908-786bdd2ae6a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
