<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Contact</name>
   <tag></tag>
   <elementGuidId>1f26e942-98fe-4fac-a8f0-f27660482813</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/nav/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>32b1d1e1-59bc-4e43-988a-ac0f5446d0ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block font-semibold uppercase tracking-widest whitespace-nowrap text-gray-300 hover:text-white hover:underline-offset-2 hover:underline transition</value>
      <webElementGuid>95dd210c-61a8-4b3a-9440-7681edcd4644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/contact/</value>
      <webElementGuid>d6910106-36e2-4114-b18c-a28545c0aeaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contact</value>
      <webElementGuid>461f0ab7-ba4a-46d8-ad51-954a42ac8a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative w-full overflow-hidden&quot;]/div[@class=&quot;fixed top-0 z-50 w-full my-6 px-4 sm:px-8 sm:my-8 transition&quot;]/nav[1]/ul[@class=&quot;flex justify-evenly sm:gap-10 sm:justify-start transition&quot;]/li[3]/a[@class=&quot;block font-semibold uppercase tracking-widest whitespace-nowrap text-gray-300 hover:text-white hover:underline-offset-2 hover:underline transition&quot;]</value>
      <webElementGuid>09df1f0e-8bee-44e9-9c23-6ad8340d77ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/nav/ul/li[3]/a</value>
      <webElementGuid>28c2b4e2-4596-4a3e-9a04-d6184948d211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Contact')]</value>
      <webElementGuid>106bba9d-21f9-4f5f-b85c-3e50e8330bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Team'])[1]/following::a[1]</value>
      <webElementGuid>6ba2cb22-6468-4176-93cf-28d5d8d26452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Services'])[1]/following::a[2]</value>
      <webElementGuid>17938bca-5bde-4770-9b40-7a47cb344262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bold &amp; Underline Communication'])[2]/preceding::a[1]</value>
      <webElementGuid>e1bd5c90-c775-46e0-8d49-a9d294fdb63a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bold &amp; Underline'])[1]/preceding::a[6]</value>
      <webElementGuid>7c80f05d-a982-4b01-8aae-f71bc8d70f63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Contact']/parent::*</value>
      <webElementGuid>773c5cc5-8a13-4f5c-98d6-f3be879b9d49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/contact/')]</value>
      <webElementGuid>bf586aa5-79c1-4b0a-87f1-5b2162b25090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>812d7565-baf1-4787-9eb6-5ea3ff73de57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/contact/' and (text() = 'Contact' or . = 'Contact')]</value>
      <webElementGuid>db1b3602-06f2-4463-b963-55a5acc72a2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
